### ISSUE TITLE
Not compatible with sanity-codegen

### ISSUE THREAD

**Issue by MarcinHenzel** [sanity-io/orderable-document-list#14]
I'm not sure if its orderable-document-list bug, but this is what happen when I try to generate new types from schema with ```npx sanity-codegen```

```
Reguire stack:
Cannot find module 'part:@sanity/base/client'
- ...node_modules\@sanity\orderable-document-list\lib\fields\orderRankField.js
- ... node_modules\@sanity\orderable-document-list\lib\index.js
- ... schemas\pages\homePage.js
- ... schemas\pages\index.ts
- ... schemas\schema.js
- ... node_modules\sanity-codegen\cli.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (C:\...\node_modules\@sanity\orderable-document-list\src\fields\orderRankField.js:1:1)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Module._compile (C:\...\node_modules\pirates\lib\index.js:136:24)
at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Object.newLoader [as .js] (C:\...\node_modules\pirates\lib\index.js:141:7)
at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'node_modules\@sanity\orderable-document-list\lib\fields\orderRankField.js',
' node_modules\@sanity\orderable-document-list\lib\index.js',
' schemas\pages\homePage.js',
' schemas\pages\index.ts',
' schemas\schema.js',
' node_modules\sanity-codegen\cli.js'
  ]

```
homePage uses orderable list
Im using "sanity-codegen": "0.9.8"     "@sanity/orderable-document-list": "0.0.4",
Is it possible to use codegen with your lib? If so then any tip would be helpful. Codegen has some babel configuration, but not sure how this could help....

**Comment by SimeonGriggs** [comment]
Believe this is an issue with Codegen, and not this plugin. Perhaps file a ticket on the `sanity-codegen` repo:
https://github.com/ricokahler/sanity-codegen/issues
