### ISSUE TITLE
Issue installing @studio-v2 plugin

### ISSUE THREAD

**Issue by mitchuman** [sanity-io/orderable-document-list#40]
Sanity GraphQL and Deploy commands have stopped working after a clean install of the @studio-v2 version.

Steps to replicate: 
1. Install @studio-v2
```sh
sanity install @sanity/orderable-document-list@studio-v2

✔ Saved lockfile

✔ Saved lockfile
Plugin '@sanity/orderable-document-list@studio-v2' installed
```
2.  Run GraphQL or Deploy command (both have same error logs)
```sh
sanity deploy
✔ Checking project info

Error: Plugin "@sanity/orderable-document-list@studio-v2" not found.
Locations tried:
  * /Users/.../packages/sanity/plugins/@sanity/orderable-document-list@studio-v2
Try running "sanity install @sanity/orderable-document-list@studio-v2"?
    at getPluginNotFoundError (~/.../node_modules/@sanity/resolver/lib/resolvePlugins.js:110:13)
    at ~/.../node_modules/@sanity/resolver/lib/resolvePlugins.js:104:13
    at async Promise.all (index 12)
```

**Comment by danjrichardson** [comment]
I've had a few issues with the cli where the v2 plugin will install, but the reference to the plugin includes @studio-v2 in the "plugins" list.
I've needed to remove the @studio-v2 at the end to get it working, at least in the desk
![image](https://user-images.githubusercontent.com/2117272/203062811-82f1ffa7-5816-4053-96ba-f5ba301aac94.png)

**Comment by mitchuman** [comment]
> I've had a few issues with the cli where the v2 plugin will install, but the reference to the plugin includes @studio-v2 in the "plugins" list, so it would read "@sanity/orderable-document-list@studio-v2" before editing. I've needed to remove the @studio-v2 at the end to get it working, at least in the desk ![image](https://user-images.githubusercontent.com/2117272/203062811-82f1ffa7-5816-4053-96ba-f5ba301aac94.png)

I've tried this and both local and the deployed studio still are broken and inaccessible.

I've downgraded to `^0.0.9` and everything is working for now.
