### ISSUE TITLE
Vite error: Could not resolve "X"

### ISSUE THREAD

**Issue by nuotsu** [sanity-io/orderable-document-list#48]
## Initial error
Vite error occurs with the following basic setup:

```ts
// sanity.config.ts
export default defineConfig({
  ...
  plugins: [
    deskTool({ structure }),
    visionTool(),
  ],
  ...
})

// structure.ts
import { orderableDocumentListDeskItem as orderable } from '@sanity/orderable-document-list'

export const structure = (S, context) =>
	S.list()
		.title('Content')
		.items([
			orderable({ type: 'neoType', S, context }),
		])
```

Error:
** Could not resolve "X". You can mark the path "X" as external to exclude it from the bundle, which will remove this error. **

```
1:20:46 PM [vite] page reload config/structure.ts
✘ [ERROR] Could not resolve "sanity"

    ../node_modules/@sanity/orderable-document-list/lib/index.esm.js:1:766:
      1 │ ...Preview as o,useClient as s}from"sanity";import{LexoRank as l}from"lexo...
        ╵                                    ~~~~~~~~

  You can mark the path "sanity" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "sanity/desk"

    ../node_modules/@sanity/orderable-document-list/lib/index.esm.js:1:1333:
      1 │ ...mport{usePaneRouter as C}from"sanity/desk";const $=e=>{if(!(null==e?voi...
        ╵                                 ~~~~~~~~~~~~~

  You can mark the path "sanity/desk" as external to exclude it from the bundle, which
  will remove this error.

✘ [ERROR] Could not resolve "styled-components"

    ../node_modules/@sanity/ui/dist/index.esm.js:62:97:
      62 │ ...der$1, useTheme as useTheme$1, css, keyframes } from 'styled-components';
         ╵                                                         ~~~~~~~~~~~~~~~~~~~

  You can mark the path "styled-components" as external to exclude it from the bundle,
  which will remove this error.

1:20:47 PM [vite] error while updating dependencies:
Error: Build failed with 3 errors:
../node_modules/@sanity/orderable-document-list/lib/index.esm.js:1:766: ERROR: Could not resolve "sanity"
../node_modules/@sanity/orderable-document-list/lib/index.esm.js:1:1333: ERROR: Could not resolve "sanity/desk"
../node_modules/@sanity/ui/dist/index.esm.js:62:97: ERROR: Could not resolve "styled-components"
    at failureErrorWithLog (/Users/~/studio/node_modules/vite/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/~/studio/node_modules/vite/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/~/studio/node_modules/vite/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/~/studio/node_modules/vite/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/~/studio/node_modules/vite/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/~/studio/node_modules/vite/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/~/studio/node_modules/vite/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/~/studio/node_modules/vite/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

## Resolve attempt
I've updated the Vite config settings to exclude the paths, but then a new error occurs:

```ts
import {defineCliConfig} from 'sanity/cli'
import {UserConfig} from 'vite'

export default defineCliConfig({
  ...
  vite: (config: UserConfig): UserConfig => ({
    ...config,
    build: {
      commonjsOptions: {
        exclude: [
          'sanity',
          'sanity/desk',
          'styled-components',
        ]
      }
    }
  })
})
```

Error:
```
1:33:45 PM [vite] Internal server error: Cannot find module '/Users/~/studio/node_modules/vite/dist/node/chunks/dep-19c40c50.js' imported from /Users/~/studio/node_modules/vite/dist/node/chunks/dep-5605cfa4.js
      at new NodeError (node:internal/errors:393:5)
      at finalizeResolution (node:internal/modules/esm/resolve:323:11)
      at moduleResolve (node:internal/modules/esm/resolve:916:10)
      at defaultResolve (node:internal/modules/esm/resolve:1124:11)
      at nextResolve (node:internal/modules/esm/loader:163:28)
      at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
      at ESMLoader.import (node:internal/modules/esm/loader:525:22)
      at importModuleDynamically (node:internal/modules/esm/translators:110:35)
      at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
      at traverseHtml (file:///Users/~/studio/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:42846:23)
      at devHtmlHook (file:///Users/~/studio/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:60536:11)
      at applyHtmlTransforms (file:///Users/~/studio/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:43387:27)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async viteIndexHtmlMiddleware (file:///Users/~/studio/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:60605:28) (x2)
```

**Comment by nuotsu** [comment]
Still unresolved. I have been unable to use this plugin on v3 (one of my most used ones in v2).

**Comment by el-schneider** [comment]
I ran into the same issue, did you find any solution?
